utrackVersion: v1.3.1

dockerRegistry:
  enabled: false
  registry: registry.utrack.tools
  loginid: ''
  password: ''

license:
  licenseServer: https://prime.getutrack.io
  licenseDomain: 'utrack.example.com'

ingress:
  enabled: true
  minioHost: ''
  rabbitmqHost: ''
  ingressClass: 'nginx'
  ingress_annotations: {
    "nginx.ingress.kubernetes.io/proxy-body-size": "5m",
  }

ssl:
  createIssuer: false
  issuer: http # Allowed : cloudflare, digitalocean, http
  token: '' # not required for http
  server: https://acme-v02.api.letsencrypt.org/directory
  email: utrack@example.com
  generateCerts: false

services:
  redis:
    local_setup: true
    image: registry.utrack.tools/utrack/valkey:7.2.5-alpine
    servicePort: 6379
    volumeSize: 500Mi
    assign_cluster_ip: false

  postgres:
    local_setup: true
    image: registry.utrack.tools/utrack/postgres:15.5-alpine
    servicePort: 5432
    cliConnectPort: ''
    volumeSize: 2Gi
    assign_cluster_ip: false

  rabbitmq:
    local_setup: true
    image: rabbitmq:3.13.6-management-alpine
    servicePort: 5672
    managementPort: 15672
    volumeSize: 100Mi
    default_user: utrack
    default_password: utrack
    external_rabbitmq_url: ''
    assign_cluster_ip: false

  minio:
    local_setup: true
    image: registry.utrack.tools/utrack/minio:latest
    volumeSize: 3Gi
    root_user: admin
    root_password: password
    assign_cluster_ip: false

  web:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    image: registry.utrack.tools/utrack/web-enterprise
    assign_cluster_ip: false

  monitor:
    memoryLimit: 1000Mi
    cpuLimit: 500m
    image: registry.utrack.tools/utrack/monitor-enterprise
    volumeSize: 100Mi
    assign_cluster_ip: false

  space:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    image: registry.utrack.tools/utrack/space-enterprise
    assign_cluster_ip: false
    
  admin:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    image: registry.utrack.tools/utrack/admin-enterprise
    assign_cluster_ip: false

  live:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    image: registry.utrack.tools/utrack/live-enterprise
    assign_cluster_ip: false

  api:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    image: registry.utrack.tools/utrack/backend-enterprise
    assign_cluster_ip: false
    
  worker:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m

  beatworker:
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m

env:
  pgdb_username: utrack
  pgdb_password: utrack
  pgdb_name: utrack
  pgdb_remote_url: '' #INCASE OF REMOTE PG DB URL ONLY

  storageClass: longhorn

  # NEXT_PUBLIC_DEPLOY_URL:  ''
  # REDIS
  remote_redis_url: '' #INCASE OF REMOTE REDIS ONLY
  # POSTGRES DB VALUES

  # DATA STORE
  docstore_bucket: uploads
  doc_upload_size_limit: '5242880' # 5MB

  # REQUIRED IF MINIO LOCAL SETUP IS FALSE
  aws_access_key: ''
  aws_secret_access_key: ''
  aws_region: ''
  aws_s3_endpoint_url: ''
  
  secret_key: "60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5"

  sentry_dsn: ''
  sentry_environment: ''

  cors_allowed_origins: ''
  instance_admin_email: ''

  live_sentry_dsn: ""
  live_sentry_environment: ""
  live_sentry_traces_sample_rate: ""

