{{- if .Values.services.rabbitmq.local_setup }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-rabbitmq-secrets
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.services.rabbitmq.default_user | default "utrack" | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.services.rabbitmq.default_password | default "utrack" | b64enc |quote }}
---

{{- end }}